<h6>Dashboard menu</h6>
            <ul>
              <li><a href="index.html"><span class="rulycon-home"></span>Home</a></li>
              <li><a href="<?php echo $this->baseUrl('vulnerable'); ?>"><span class="rulycon-bug"></span>Vulnerable check</a></li>
              <li><a href="mac-address-log.html"><span class="rulycon-file"></span>MAC address log</a></li>
              <li><a href="access-history.html"><span class="rulycon-upload-3"></span>Access history</a></li>
              <li><a href="bandwith-rules.html"><span class="rulycon-tree"></span>Bandwith rules</a></li>
              <li><a href="port-and-services.html"><span class="rulycon-switch"></span>Port &amp; Services</a></li>
              <li><a href="alert-and-notification.html"><span class="rulycon-spam"></span>Alert &amp; Notification</a></li>
            </ul>
</div>