
      <!-- HOME PAGE-->
      <div class="row">
        <div class="col-lg-12">
          <h1 id="page-title"><span>·<span>·</span>· Dashboard ·<span>·</span>·</span></h1>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div id="summary-wrapper">
            <ul id="summary-tab" class="nav nav-tabs">
              <li class="active"><a href="#bandwith-usage-summary" data-toggle="tab">Bandwith usage summary</a></li>
              <li><a href="#vulnerability-summary" data-toggle="tab">Vulnerability summary</a></li>
            </ul>
            <div id="summary-tab-content" class="tab-content">
              <div id="bandwith-usage-summary" class="tab-pane active">
                <div id="chart-container">
                  <div id="bandwith-usage-summary"></div>
                </div>
              </div>
              <div id="vulnerability-summary" class="tab-pane">
                <div id="chart-container">
                  <div id="vulnerability-summary"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <script type="text/javascript">
        $(document).ready(function() {
          $(function() {
            $.getJSON('http://www.highcharts.com/samples/data/jsonp.php?filename=aapl-c.json&callback=?', function(data) {
              // Create the chart
              window.chart = new Highcharts.StockChart({
                chart : { renderTo : 'bandwith-usage-summary' },
                rangeSelector : { selected : 1 },
                title : { text : 'Bandwith Usage summary' },
                series : [{ name : 'AAPL', data : data, tooltip: { yDecimals: 2 } }]
              });
            });
          });
          
          $(function() {
            $.getJSON('http://www.highcharts.com/samples/data/jsonp.php?filename=aapl-c.json&callback=?', function(data) {
              // Create the chart
              window.chart = new Highcharts.StockChart({
                chart : { renderTo : 'vulnerability-summary' },
                rangeSelector : { selected : 1 },
                title : { text : 'Vulnerability summary' },
                series : [{
                  name : 'AAPL Stock Price', data : data, marker : { enabled : true, radius : 3 },
                  shadow : true,
                  tooltip : { yDecimals : 2 }
                }]
              });
            });
          });
        });
      </script>