<!-- MAC ADDRESS LOG PAGE-->
<div class="row">
    <div class="col-lg-12">
        <h1 id="page-title"><span>·<span>·</span>· MAC address log ·<span>·</span>·</span></h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <form class="form-inline">
            <div class="form-group">
                <label>Start time</label>
                <input id="start-time" class="datepicker">
                <label>End time</label>
                <input id="end-time" class="datepicker">
                <button class="btn btn-lemhannas" id="submit-date">Show vulnerability data</button>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <!-- property untuk datatable -->
        <table id="mac-address-log-table" class="table table-hover table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>MAC</th>
                <th>Hostname</th>
                <th>Operating system</th>
                <th>Bandwith usage</th>
                <th>Status</th>
<!--                <th>Modify</th>-->
            </tr>
            </thead>
        </table>
        <form class="form-inline">
            <div class="form-group">
                <label>Auto-update every</label>
                <select id="auto-update">
                    <option value="0">~select auto-update period~</option>
                    <option value="1">15 detik</option>
                    <option value="2">30 detik</option>
                    <option value="3">1 menit</option>
                    <option value="4">3 menit</option>
                    <option value="5">5 menit</option>
                </select>
                <button class="btn btn-lemhannas pull-right">Refresh</button>
            </div>
        </form>
    </div>
</div>
<!-- PUT ALL MODALS BELOW-->
<div id="add-modal" tab-index="-1" role="dialog" aria-labelledby="add-modal-label" aria-hidden="true" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" data-dismiss="modal" aria-hidden="true" class="close">×</button>
                <h4 id="add-modal-lable" class="modal-title">Add</h4>
            </div>
            <div class="modal-body">
                <form role="form" class="form-horizontal">
                    <div class="form-group">
                        <label class="col-lg-3 control-label">MAC address</label>
                        <div class="col-lg-9">
                            <input type="text" placeholder="type MAC address here..." value="192.168.0.193" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label">Hostname</label>
                        <div class="col-lg-9">
                            <input type="text" placeholder="type hostname here..." value="fulan-06-PC" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label">Description</label>
                        <div class="col-lg-9">
                            <textarea rows="4" placeholder="type description here..." class="form-control"></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label">Is blocked</label>
                        <div class="col-lg-9">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox">
                                </label>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-lemhannas">Add</button>
                <button type="button" data-dismiss="modal" class="btn btn-lemhannas">Cancel</button>
            </div>
        </div>
    </div>
</div>
<div id="delete-modal" tab-index="-1" role="dialog" aria-labelledby="delete-modal-label" aria-hidden="true" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" data-dismiss="modal" aria-hidden="true" class="close">×</button>
                <h4 id="delete-modal-lable" class="modal-title">Delete</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete the selected item?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-lemhannas btn-red">Yes, delete</button>
                <button type="button" data-dismiss="modal" class="btn btn-lemhannas">Cancel</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    var interval = null;
//    var $tbl_data;

var oTable = $('#mac-address-log-table').dataTable( {
    "bJQueryUI": true,
    "sScrollX": "",
    "bSortClasses": false,
    "aaSorting": [[0,'asc']],
    "bAutoWidth": true,
    "bInfo": true,
    "aoColumns":[
        {bSortable:false},
        null,
        null,
        null,
        null,
        null
    ],
    "sScrollY": "100%",
    "sScrollX": "100%",
    "bScrollCollapse": true,
    "sPaginationType": "full_numbers",
    "bProcessing" : true,
    "bServerSide" : true,
    "sAjaxSource" : baseUrl + '/macaddresslog/datatable',
    "fnServerData" : function(sSource, aoData, fnCallback)
    {
        //filter category content
        if(jQuery('#feed-filter').length)
        {
            filter = jQuery('#feed-filter').val()

            aoData.push({
                "name": "filter",
                "value":  filter
            });
        }

        jQuery.getJSON(sSource, aoData, function(json) {
            //if(aaData != 'undefined')
            //{
            fnCallback(json)
            //}
        });

        $('.custom-rows').parent().css('vertical-align','middle');
    }
});

    $('#submit-date').click(function(){
        oTable.fnDraw();
    });

    $('#refresh').click(function(){
        oTable.fnDraw();
    });

    $('#auto-update').change(function(){
        switch ($('#auto-update').val())
        {
            case '0':
                stopInterval();
                break;
            case '1':
                startInterval(2000);
                break;
            case '2':
                startInterval(30000);
                break;
            case '3':
                startInterval(60000);
                break;
            case '4':
                startInterval(180000);
                break;
            case '5':
                startInterval(600000);
                break;
        }
    });

    function startInterval(time)
    {
        interval = setInterval(function(){
            oTable.fnDraw();
        }, time)
    }

    function stopInterval()
    {
        clearInterval(interval);
    }

//    var tbl_data = $("#mac-address-log-table").dataTable({
//        bFilter: false,
//        bInfo: false,
//        bSort: false,
//        bPaginate: true,
//        bLengthChange: false,
//        bServerSide: true,
//        bProcessing: true,
//        sAjaxSource: baseUrl + "/macaddresslog/datatables",
//        aoColumns: [
//            {bSortable:false},{mData: "MacAddress"}, {mData: "Hostname"}, {mData: "OperatingSystem"}, {bSortable:false},{bSortable:false},{bSortable:false}
//        ],
//        fnServerData: function(sSource, aoData, fnCallback) {
//            //filter category content
//            if(jQuery('#feed-filter').length)
//            {
//                filter = jQuery('#feed-filter').val()
//
//                aoData.push({
//                    "name": "filter",
//                    "value":  filter
//                });
//            }
//
//            jQuery.getJSON(sSource, aoData, function(json) {
//                //if(aaData != 'undefined')
//                //{
//                fnCallback(json)
//                //}
//            });
//
//            $('.custom-rows').parent().css('vertical-align','middle');
//        }
//    });
</script>