<!-- VULNERABLE CHECK PAGE-->
      <div class="row">
        <div class="col-lg-12">
          <h1 id="page-title"><span>·<span>·</span>· Vulnerable check ·<span>·</span>·</span></h1>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <form class="form-inline">
            <div class="form-group">
              <label>Start time</label>
              <select id="start_time">
                <option>~select start time~</option>
                <option>ganti pake date picker</option>
              </select>
              <label>End time</label>
              <select id="start_time">
                <option>~select end time~</option>
                <option>ganti pake date picker</option>
              </select>
              <button class="btn btn-lemhannas">Show vulnerability data</button>
            </div>
          </form>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <table class="table table-hover table-striped" id="data_table">
            <thead>
              <tr>
                <th>#</th>
                <th>MAC</th>
                <th>Hostname</th>
                <th>Operating system</th>
                <th>Bandwith usage</th>
                <th>Vulnerability</th>
              </tr>
            </thead>
          </table>
          <form class="form-inline">
            <div class="form-group">
              <label>Auto-update every</label>
              <select>
                <option>~select auto-update period~</option>
                <option>15 detik</option>
                <option>30 detik</option>
                <option>1 menit</option>
                <option>3 menit</option>
                <option>5 menit</option>
              </select>
              <button class="btn btn-lemhannas pull-right">Refresh</button>
            </div>
          </form>
        </div>
      </div>

<script type="text/javascript">
    var oTable = $('#data_table').dataTable( {
        "bJQueryUI": true,
        "sScrollX": "",
        "bSortClasses": false,
        "aaSorting": [[0,'asc']],
        "bAutoWidth": true,
        "bInfo": true,
        "aoColumns":[
            {bSortable:false},
            null,
            null,
            null,
            null,
            null,
        ],
        "sScrollY": "100%",
        "sScrollX": "100%",
        "bScrollCollapse": true,
        "sPaginationType": "full_numbers",
        "bProcessing" : true,
        "bServerSide" : true,
        "sAjaxSource" : baseUrl + '/vulnerable/datatable',
        "fnServerData" : function(sSource, aoData, fnCallback)
        {
            //filter category content
            if(jQuery('#feed-filter').length)
            {
                filter = jQuery('#feed-filter').val()

                aoData.push({
                    "name": "filter",
                    "value":  filter
                });
            }

            jQuery.getJSON(sSource, aoData, function(json) {
                //if(aaData != 'undefined')
                //{
                fnCallback(json)
                //}
            });

            $('.custom-rows').parent().css('vertical-align','middle');
        }
    });
</script>