<!-- VULNERABLE CHECK PAGE-->
      <div class="row">
        <div class="col-lg-12">
          <h1 id="page-title"><span>·<span>·</span>· Vulnerable check ·<span>·</span>·</span></h1>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <form class="form-inline">
            <div class="form-group">
              <label>Start time</label>
              <select>
                <option>~select start time~</option>
                <option>ganti pake date picker</option>
              </select>
              <label>End time</label>
              <select>
                <option>~select end time~</option>
                <option>ganti pake date picker</option>
              </select>
              <button class="btn btn-lemhannas">Show vulnerability data</button>
            </div>
          </form>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <table class="table table-hover table-striped">
            <thead>
              <tr>
                <th>#</th>
                <th>MAC</th>
                <th>Hostname</th>
                <th>Operating system</th>
                <th>Bandwith usage</th>
                <th>Vulnerability</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>1</td>
                <td>00-00</td>
                <td>fulan-01-PC</td>
                <td>Microsoft Windows 7 x86</td>
                <td>1200 Mbps</td>
                <td>3</td>
              </tr>
              <tr>
                <td>2</td>
                <td>00-01</td>
                <td>fulan-02-PC</td>
                <td>Redhat Enterprise Linux 1.0</td>
                <td>1200 Mbps</td>
                <td>5</td>
              </tr>
              <tr>
                <td>3</td>
                <td>00-02</td>
                <td>fulan-03-PC</td>
                <td>Microsoft Windows 8 x64</td>
                <td>1200 Mbps</td>
                <td>7</td>
              </tr>
              <tr>
                <td>4</td>
                <td>00-03</td>
                <td>fulan-04-PC</td>
                <td>Microsoft Windows 8 x64</td>
                <td>1200 Mbps</td>
                <td>4</td>
              </tr>
              <tr>
                <td>5</td>
                <td>00-04</td>
                <td>fulan-05-PC</td>
                <td>Microsoft Windows 7 x64</td>
                <td>1200 Mbps</td>
                <td>2</td>
              </tr>
              <tr>
                <td>6</td>
                <td>00-05</td>
                <td>fulan-06-PC</td>
                <td>Ubuntu 12.0.1</td>
                <td>1200 Mbps</td>
                <td>8</td>
              </tr>
              <tr>
                <td>7</td>
                <td>00-06</td>
                <td>multimedia-01-PC</td>
                <td>Microsoft Windows XP</td>
                <td>3000 Mbps</td>
                <td>6</td>
              </tr>
              <tr class="danger">
                <td>8</td>
                <td>00-07</td>
                <td>multimedia-02-PC</td>
                <td>Microsoft Windows XP</td>
                <td>3000 Mbps</td>
                <td>10</td>
              </tr>
              <tr>
                <td>9</td>
                <td>00-08</td>
                <td>multimedia-03-PC</td>
                <td>MacOS X Mavericks</td>
                <td>3000 Mbps</td>
                <td>1</td>
              </tr>
              <tr>
                <td>10</td>
                <td>00-09</td>
                <td>multimedia-04-PC</td>
                <td>MacOS X Mavericks</td>
                <td>3000 Mbps</td>
                <td>2</td>
              </tr>
              <tr>
                <td>11</td>
                <td>00-00</td>
                <td>fulan-01-PC</td>
                <td>Microsoft Windows 7 x86</td>
                <td>1200 Mbps</td>
                <td>3</td>
              </tr>
              <tr>
                <td>12</td>
                <td>00-01</td>
                <td>fulan-02-PC</td>
                <td>Redhat Enterprise Linux 1.0</td>
                <td>1200 Mbps</td>
                <td>5</td>
              </tr>
              <tr>
                <td>13</td>
                <td>00-02</td>
                <td>fulan-03-PC</td>
                <td>Microsoft Windows 8 x64</td>
                <td>1200 Mbps</td>
                <td>7</td>
              </tr>
              <tr>
                <td>14</td>
                <td>00-03</td>
                <td>fulan-04-PC</td>
                <td>Microsoft Windows 8 x64</td>
                <td>1200 Mbps</td>
                <td>4</td>
              </tr>
              <tr>
                <td>15</td>
                <td>00-04</td>
                <td>fulan-05-PC</td>
                <td>Microsoft Windows 7 x64</td>
                <td>1200 Mbps</td>
                <td>2</td>
              </tr>
              <tr>
                <td>16</td>
                <td>00-05</td>
                <td>fulan-06-PC</td>
                <td>Ubuntu 12.0.1</td>
                <td>1200 Mbps</td>
                <td>8</td>
              </tr>
              <tr>
                <td>17</td>
                <td>00-06</td>
                <td>multimedia-01-PC</td>
                <td>Microsoft Windows XP</td>
                <td>3000 Mbps</td>
                <td>6</td>
              </tr>
              <tr>
                <td>18</td>
                <td>00-07</td>
                <td>multimedia-02-PC</td>
                <td>Microsoft Windows XP</td>
                <td>3000 Mbps</td>
                <td>3</td>
              </tr>
              <tr>
                <td>19</td>
                <td>00-08</td>
                <td>multimedia-03-PC</td>
                <td>MacOS X Mavericks</td>
                <td>3000 Mbps</td>
                <td>1</td>
              </tr>
              <tr>
                <td>20</td>
                <td>00-09</td>
                <td>multimedia-04-PC</td>
                <td>MacOS X Mavericks</td>
                <td>3000 Mbps</td>
                <td>2</td>
              </tr>
            </tbody>
          </table>
          <form class="form-inline">
            <div class="form-group">
              <label>Auto-update every</label>
              <select>
                <option>~select auto-update period~</option>
                <option>15 detik</option>
                <option>30 detik</option>
                <option>1 menit</option>
                <option>3 menit</option>
                <option>5 menit</option>
              </select>
              <button class="btn btn-lemhannas pull-right">Refresh</button>
            </div>
          </form>
        </div>
      </div>