<style type="text/css">
    br { clear: both; }
    .cntSeparator {
        font-size: 54px;
        margin: 10px 7px;
        color: #000;
    }
    .desc { margin: 7px 3px; }
    .desc div {
        float: left;
        font-family: Arial;
        width: 70px;
        margin-right: 65px;
        font-size: 13px;
        font-weight: bold;
        color: #000;
    }
</style>
<!-- VULNERABLE CHECK PAGE-->
      <div class="row">
        <div class="col-lg-12">
          <h1 id="page-title"><span>·<span>·</span>· Vulnerable check ·<span>·</span>·</span></h1>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <form class="form-inline">
            <div class="form-group">
              <label>Start time</label>
              <input id="start-time" class="datepicker">
              <label>End time</label>
              <input id="end-time" class="datepicker">
              <button class="btn btn-lemhannas" id="submit-date">Show vulnerability data</button>
            </div>
          </form>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <table class="table table-hover table-striped" id="data_table">
            <thead>
              <tr>
                <th>#</th>
                <th>MAC</th>
                <th>Hostname</th>
                <th>Operating system</th>
                <th>Bandwith usage</th>
                <th>Vulnerability</th>
              </tr>
            </thead>
          </table>
          <form class="form-inline">
            <div class="form-group">
              <label>Auto-update every</label>
              <select id="auto-update">
                <option value="0">~select auto-update period~</option>
                <option value="1">15 detik</option>
                <option value="2">30 detik</option>
                <option value="3">1 menit</option>
                <option value="4">3 menit</option>
                <option value="5">5 menit</option>
              </select>
              <button class="btn btn-lemhannas pull-right" id="refresh">Refresh</button>
            </div>
          </form>
        </div>
      </div>

<script type="text/javascript">
    var interval = null;
    var oTable = $('#data_table').dataTable( {
        "bJQueryUI": true,
        "sScrollX": "",
        "bSortClasses": false,
        "aaSorting": [[0,'asc']],
        "bAutoWidth": true,
        "bInfo": true,
        "aoColumns":[
            {bSortable:false},
            null,
            null,
            null,
            null,
            null
        ],
        "sScrollY": "100%",
        "sScrollX": "100%",
        "bScrollCollapse": true,
        "sPaginationType": "full_numbers",
        "bProcessing" : true,
        "bServerSide" : true,
        "sAjaxSource" : baseUrl + '/vulnerable/datatable',
        "fnServerData" : function(sSource, aoData, fnCallback)
        {
            //filter category content
            if(jQuery('#feed-filter').length)
            {
                var start_date = jQuery('#start-date').val();
                var end_date = jQuery('#end-date').val();

                aoData.push({
                    "name": "start_date",
                    "value":  start_date
                },{
                    "name": "end_date",
                    "value":  end_date
                });
            }

            jQuery.getJSON(sSource, aoData, function(json) {
                //if(aaData != 'undefined')
                //{
                fnCallback(json)
                //}
            });

            $('.custom-rows').parent().css('vertical-align','middle');
        }
    });

    $('#submit-date').click(function(){
        oTable.fnDraw();
    });

    $('#refresh').click(function(){
        oTable.fnDraw();
    });

    $('#auto-update').change(function(){
        switch ($('#auto-update').val())
        {
            case '0':
                stopInterval();
                break;
            case '1':
                startInterval(2000);
                break;
            case '2':
                startInterval(30000);
                break;
            case '3':
                startInterval(60000);
                break;
            case '4':
                startInterval(180000);
                break;
            case '5':
                startInterval(600000);
                break;
        }
    });

    function startInterval(time)
    {
        interval = setInterval(function(){
            oTable.fnDraw();
        }, time)
    }

    function stopInterval()
    {
        clearInterval(interval);
    }
</script>